# syntax=docker/dockerfile:1

FROM node:18-alpine
WORKDIR /app
#COPY . .
#RUN yarn install --production
#RUN npm install nodemon
RUN yarn install
#RUN yarn run dev
ENTRYPOINT ["yarn","run", "dev"]
EXPOSE 3000
